onlineFeedStore/goods/urls.py
from django.urls import path
from goods import views

app_name = "goods"

urlpatterns = [
    path("", views.catalog, name="index"),
    path("<slug:category_slug>/", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product"),
]

onlineFeedStore/main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("contacts", views.contacts, name="contacts"),
    path("feedback", views.feedback, name="feedback"),
]

onlineFeedStore/onlineFeedStore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "onlineFeedStore.views.error_404_view"

onlineFeedStore/users/urls.py
from django.urls import path

from users import views


app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("users-cart/", views.users_cart, name="users_cart"),
    path("logout/", views.logout, name="logout"),
]

onlineFeedStore/orders/models.py
from django.db import models
from goods.models import Products

from users.models import User


class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name="Требуется доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при получении")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(
        max_length=50,
        default='В обработке',
        choices=(('В обработке', 'В обработке'), ('Отправлен', 'Отправлен'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')),
        verbose_name="Статус заказа"
    )

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        if self.user is not None:
            return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"
        else:
            return f"Заказ № {self.pk} | Покупатель удалил аккаунт"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"
  

onlineFeedStore/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        db_table = "user"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

onlineFeedStore/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ["username", "password"]
    
    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",)
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

onlineFeedStore/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm
from carts.models import Cart
from orders.models import Order, OrderItem


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                if session_key:
                    if Cart.objects.filter(session_key=session_key).exists():
                        Cart.objects.filter(user=user).delete()
                        Cart.objects.filter(session_key=session_key).update(user=user)


                redirect_page = request.POST.get("next", None)
                if redirect_page and redirect_page != reverse("user:logout"):
                    return HttpResponseRedirect(request.POST.get("next"))

                return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserLoginForm()

    context = {
        "title": "Авторизация | АвтоМир",
        "form": form,
    }
    return render(request, "users/login.html", context)


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(
                request,
                f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт",
            )
            return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserRegistrationForm()

    context = {
        "title": "Регистрация | АвтоМир",
        "form": form,
    }
    return render(request, "users/registration.html", context)


def users_cart(request):
    return render(
        request, "users/users_cart.html", {"title": "Корзина | АвтоМир"}
    )


@login_required
def profile(request):
    if request.method == "POST":
        form = ProfileForm(
            data=request.POST, instance=request.user, files=request.FILES
        )
        if form.is_valid():
            form.save()
            messages.success(request, "Профиль успешно обновлен")
            return HttpResponseRedirect(reverse("user:profile"))
    else:
        form = ProfileForm(instance=request.user)

    orders = (
        Order.objects.filter(user=request.user)
        .prefetch_related(
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related("product"),
            )
        )
        .order_by("-id")
    )

    context = {
        "title": "Профиль | АвтоМир",
        "form": form,
        "orders": orders,
    }
    return render(request, "users/profile.html", context)


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse("main:index"))

onlineFeedStore/users/templates/users/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ title }}{%endblock %} 


{% block header %}

{% include 'includes/header.html' %}

{% endblock %}


{% block content %}


<section
    class="login-form"
    
   >
    <div class="container">
      {% include 'includes/notif_login.html' %}
      <div class="login-form__inner">
        <h4 class="login-form__title">Авторизация</h4>
        <form action="{% url "user:login" %}" method="post" class="login-form__form">
          {% csrf_token %}

          
          {% if request.GET.next %}
            <input type="hidden" name="next" value={{request.GET.next}}>
          {% endif %}
          <div class="login-form__groups">
            <div class="login-form__group">
              <label for="id_username" class="login-form__label">Имя пользователя</label>
              <input 
                type="text" 
                class="login-form__input" 
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                name="username" 
                id="id_username" 
                placeholder="Ваше имя пользователя" 
                required/>
            </div>
            <div class="login-form__group">
              <label for="id_password" class="login-form__label">Пароль</label>
              <input
                type="password"
                class="login-form__input"
                name="password"
                id="id_password"
                placeholder="Ваш пароль"
                required
              />
            </div>
            <div class="login-form__group-break"></div>
            <button class="login-form__btn" type="submit">
              Войти
            </button>
          </div>
        </form>
        <div class="login-form__description" >
          <a class="login-form__description-link" href="{% url "user:registration" %}"></a><a class="login-form__description-link" href="{% url "user:registration" %}">Создать аккаунт</a>
        </div>
      </div>
    </div>
</section>


{% endblock %}

onlineFeedStore/users/templates/users/profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ title }}{%endblock %} 


{% block header %}

{% include 'includes/header.html' %}

{% endblock %}


{% block content %}

<section class="profile">
    <div class="container">
      <div class="profile__inner">

        <div class="user-data">
          <h2 class="user-data__title">Профиль пользователя</h2>
          <form class="form" action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="user-data-form__groups">
                <div class="user-data-form__group-break"></div>
                <div class="form__group">
                  <label for="id_first_name" class="user-data-form__label">Имя</label>
                  <input 
                    type="text" 
                    class="user-data-form__input" 
                    id="id_first_name" 
                    value="{{ form.first_name.value }}" 
                    name="first_name" 
                    placeholder="Иван" 
                    required
                  />
                  {% if form.first_name.errors %}
                  <div class="form__error">{{form.first_name.errors}}</div>
                  {% endif %}
                </div>
                <div class="form__group">
                  <label for="id_last_name" class="user-data-form__label">Фамилия</label>
                  <input 
                    type="text" 
                    class="user-data-form__input" 
                    id="id_last_name"
                    value="{{ form.last_name.value }}" 
                    name="last_name"
                    placeholder="Иванов" 
                    required
                  />
                  {% if form.last_name.errors %}
                  <div class="form__error">{{form.last_name.errors}}</div>
                  {% endif %}
                </div>
                <div class="form__group">
                  <label for="id_username" class="user-data-form__label">Имя пользователя</label>
                  <input 
                    type="text" 
                    class="user-data-form__input" 
                    id="id_username"
                    value="{{ form.username.value }}" 
                    name="username" 
                    placeholder="Ваше имя пользователя" 
                    required
                  />
                  {% if form.username.errors %}
                  <div class="form__error">{{form.username.errors}}</div>
                  {% endif %}
                </div>
                <div class="form__group">
                  <label for="id_email" class="user-data-form__label"
                    >Адрес электронной почты</label
                  >
                  <input
                    type="email"
                    class="user-data-form__input"
                    id ="id_email"
                    value="{{ form.email.value }}" 
                    name="email"
                    placeholder="example@gmail.com"
                    required
                  />
                  {% if form.email.errors %}
                  <div class="form__error">{{form.email.errors}}</div>
                  {% endif %}
                </div>
                <div class="user-data-form__group-break"></div>
                <button class="form__btn user-data-form__btn" type="submit">
                  Сохранить
                </button>
                
              </div>
            </form>
        </div>
        
        <div class="orders" id="orders">
          <h2 class="orders__title">Мои заказы</h2>
          <div class="orders-tabs">
            {% if orders %}
            {% for order in orders %}
            <div class="orders-tab">
              {% if order.status == "Доставлен" %}
              <button class="orders-tab__btn orders-tab__btn_green">
                <div class="orders-tab__btn-text">
                  <p class="orders-tab__btn-text">
                    Заказ № {{ order.id }} - {{ order.created_timestamp }} |
                  </p>
                  <p class="orders-tab__btn-text">
                    Статус: <strong>{{ order.status }}</strong>
                  </p>
                </div>
                <img
                  src="{% static "images/arrow-end-down.svg" %}"
                  alt="..."
                  class="orders-tab__btn-img"
                />
              </button>
              {% elif order.status == "Отменен" %}
              <button class="orders-tab__btn orders-tab__btn_red">
                <div class="orders-tab__btn-text">
                  <p class="orders-tab__btn-text">
                    Заказ № {{ order.id }} - {{ order.created_timestamp }} |
                  </p>
                  <p class="orders-tab__btn-text">
                    Статус: <strong>{{ order.status }}</strong>
                  </p>
                </div>
                <img
                  src="{% static "images/arrow-end-down.svg" %}"
                  alt="..."
                  class="orders-tab__btn-img"
                />
              </button>
              {% elif order.status == "Отправлен" %}
              <button class="orders-tab__btn orders-tab__btn_blue">
                <div class="orders-tab__btn-text">
                  <p class="orders-tab__btn-text">
                    Заказ № {{ order.id }} - {{ order.created_timestamp }} |
                  </p>
                  <p class="orders-tab__btn-text">
                    Статус: <strong>{{ order.status }}</strong>
                  </p>
                </div>
                <img
                  src="{% static "images/arrow-end-down.svg" %}"
                  alt="..."
                  class="orders-tab__btn-img"
                />
              </button>
              {% else %}
              <button class="orders-tab__btn">
                <div class="orders-tab__btn-text">
                  <p class="orders-tab__btn-text">
                    Заказ № {{ order.id }} - {{ order.created_timestamp }} |
                  </p>
                  <p class="orders-tab__btn-text">
                    Статус: <strong>{{ order.status }}</strong>
                  </p>
                </div>
                <img
                  src="{% static "images/arrow-end-down.svg" %}"
                  alt="..."
                  class="orders-tab__btn-img"
                />
              </button>
              {% endif %}
              <div class="orders-tab__content">
                <table class="orders-tab__table">
                  <thead>
                      <tr>
                          <th>Товар</th>
                          <th>Количество</th>
                          <th>Цена</th>
                          <th>Стоимость</th>
                      </tr>
                  </thead>
                  <tbody>
                    {% for item in order.orderitem_set.all %}
                      <tr>
                          <td><a href="{% url "goods:product" item.product.slug %}">{{ item.product.name }}</a></td>
                          <td>{{ item.quantity }}</td>
                          <td>{{ item.price }} &#x20bd;</td>
                          <td>{{ item.products_price }}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
                <div class="orders-tab__total-price">
                    <p><strong>Итого:</strong></p>
                    <p><strong>{{ order.orderitem_set.total_price }} &#x20bd;</strong></p>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}
            <p class="orders-tabs__not-orders-text" >У вас нет заказов</p>
            {% endif %}

          </div>
        </div>
        
      </div>
    </div>
</section>

{% endblock %}

onlineFeedStore/users/templates/users/registration.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ title }}{%endblock %} 


{% block header %}

{% include 'includes/header.html' %}

{% endblock %}


{% block content %}

<section
    class="login-form"
   >
    <div class="container">
      <div class="login-form__inner">
        <h4 class="login-form__title">Регистрация</h4>
        <form action="{% url "user:registration" %}" method="post" class="login-form__form">
          {% csrf_token %}

          <div class="login-form__groups">
            <div class="login-form__group">
              <label for="id_first_name" class="login-form__label">Имя</label>
              <input 
                type="text" 
                class="login-form__input" 
                id="id_first_name" 
                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" 
                name="first_name" 
                placeholder="Иван" 
                required
              />
              {% if form.first_name.errors %}
              <div class="form__error">{{form.first_name.errors}}</div>
              {% endif %}
            </div>
            <div class="login-form__group">
              <label for="id_last_name" class="login-form__label">Фамилия</label>
              <input 
                type="text" 
                class="login-form__input" 
                id="id_last_name"
                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" 
                name="last_name"
                placeholder="Иванов" 
                required
              />
              {% if form.last_name.errors %}
              <div class="form__error">{{form.last_name.errors}}</div>
              {% endif %}
            </div>
            <div class="login-form__group">
              <label for="id_username" class="login-form__label">Имя пользователя</label>
              <input 
                type="text" 
                class="login-form__input" 
                id="id_username"
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                name="username" 
                placeholder="Ваше имя пользователя" 
                required
              />
              {% if form.username.errors %}
              <div class="form__error">{{form.username.errors}}</div>
              {% endif %}
            </div>
            <div class="login-form__group">
              <label for="id_email" class="login-form__label"
                >Адрес электронной почты</label
              >
              <input
                type="email"
                class="login-form__input"
                id ="id_email"
                value="{% if form.email.value %}{{ form.email.value }}{% endif %}" 
                name="email"
                placeholder="example@gmail.com"
                required
              />
              {% if form.email.errors %}
              <div class="form__error">{{form.email.errors}}</div>
              {% endif %}
            </div>
            <div class="login-form__group">
              <label for="id_password1" class="login-form__label">Пароль</label>
              <input
                type="password"
                class="login-form__input"
                id="id_password1"
                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}" 
                name="password1"
                placeholder="Введите пароль"
                required
              />
              {% if form.password1.errors %}
              <div class="form__error">{{form.password1.errors}}</div>
              {% endif %}
            </div>
            <div class="login-form__group">
              <label for="id_password2" class="login-form__label">Подтверждение пароля</label>
              <input
                type="password"
                class="login-form__input"
                id="id_password2"
                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}" 
                name="password2"
                placeholder="Подтвердите пароль"
                required
              />
              {% if form.password2.errors %}
              <div class="form__error">{{form.password2.errors}}</div>
              {% endif %}
            </div>
            <div class="login-form__group-break"></div>
            <button class="login-form__btn reg-form__btn" type="submit">
              Зарегистрироваться
            </button>
          </div>

        </form>
      </div>
    </div>
</section>

{% endblock %}

onlineFeedStore/users/templates/users/users_cart.html
{% extends 'base.html' %}

{% load static %}

{% load carts_tags %}

{% block title %}{{ title }}{% endblock %} 


{% block header %}

{% include 'includes/header_no_cart.html' %}

{% endblock %}


{% block content %}

{% user_carts request as carts %}
<section class="cart">
  <div class="container">
    <div class="cart__inner">

      <h4 class="cart__title">Корзина</h4>

      <div id="cart-items-container">
        {% include "carts/includes/included_cart.html" %}
      </div>
      
    </div>
  </div>
</section>

{% endblock %}