onlineFeedStore/carts/urls.py
from django.urls import path
from carts import views

app_name = "carts"

urlpatterns = [
    path('cart-add/', views.cart_add, name='cart_add'),
    path('cart-change/', views.cart_change, name='cart_change'),
    path('cart-remove/', views.cart_remove, name='cart_remove'),
]

onlineFeedStore/main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("contacts", views.contacts, name="contacts"),
    path("feedback", views.feedback, name="feedback"),
]

onlineFeedStore/onlineFeedStore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "onlineFeedStore.views.error_404_view"

onlineFeedStore/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

onlineFeedStore/carts/models.py
from django.db import models

from goods.models import Products
from users.models import User

class CartQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'cart'
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"
        ordering = ("id",)

    objects = CartQueryset().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        if self.user:
            return f'Корзина {self.user.username} | Товар {self.product.name} | Количество {self.quantity}'

        return f'Анонимная корзина | Товар {self.product.name} | Количество {self.quantity}'
 

onlineFeedStore/carts/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse

from goods.models import Products
from carts.models import Cart
from carts.utils import get_user_carts


def cart_add(request):

    product_id = request.POST.get("product_id")

    product = get_object_or_404(Products, id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)

    else:
        carts = Cart.objects.filter(
            session_key=request.session.session_key, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(
                session_key=request.session.session_key, product=product, quantity=1)

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html,
    }

    return JsonResponse(response_data)


def cart_change(request):

    cart_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    cart = Cart.objects.get(id=cart_id)

    cart.quantity = quantity
    cart.save()

    user_cart = get_user_carts(request)

    current_path = '/'+'/'.join(request.META['HTTP_REFERER'].split('/')[3:])
    order_url = reverse("orders:create_order")

    if current_path == order_url:
        order = True
    else:
        order = False

    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart, "order": order}, request=request
    )

    if len(user_cart) == 0 and current_path == order_url:
        redirect_to_home = True
    else:
        redirect_to_home = False

    response_data = {
        "message": "Количество изменено",
        "cart_items_html": cart_items_html,
        "redirect_to_home": redirect_to_home
    }

    return JsonResponse(response_data)


def cart_remove(request):

    cart_id = request.POST.get("cart_id")

    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()

    user_cart = get_user_carts(request)

    current_path = '/'+'/'.join(request.META['HTTP_REFERER'].split('/')[3:])
    order_url = reverse("orders:create_order")

    if current_path == order_url:
        order = True
    else:
        order = False

    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart, "order": order}, request=request
    )

    if len(user_cart) == 0 and current_path == order_url:
        redirect_to_home = True
    else:
        redirect_to_home = False

    response_data = {
        "message": "Товар удален",
        "cart_items_html": cart_items_html,
        "quantity_deleted": quantity,
        "redirect_to_home": redirect_to_home
    }

    return JsonResponse(response_data)

onlineFeedStore/carts/templates/carts/includes/included_cart.html
{% load static %}
{% load carts_tags %}

{% user_carts request as carts %}


<div class="cart-product">
    {% for cart in carts %}
        <div class="cart-product__header">
            <h5 class="cart-product__title">{{ cart.product.name }}</h5>
        </div>
        <ul class="cart-product__list">
            <li class="cart-product__list-item">
                <div class="cart-product__info">
                    <div class="cart-product__quantity">
                        <div class="cart-product__quantity-group input-group">
                            <span class="cart-product__quantity-input-group-btn">
                                <button type="button" class="cart-product__quantity-input-btn decrement"
                                    data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "cart:cart_change" %}">
                                    {% csrf_token %}-</button>
                            </span>
                            <input type="text" class="cart-product__quantity-input number" value="{{ cart.quantity }}"
                                readonly>
                            <span class="cart-product__quantity-input-group-btn">
                                <button type="button" class="cart-product__quantity-input-btn increment"
                                    data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "cart:cart_change" %}">
                                    {% csrf_token %}+</button>
                            </span>
                        </div>
                    </div>

                    <div class="cart-product__price">
                        <p class="cart-product__price-text">x {{ cart.product.sell_price }} = </p>
                    </div>

                    <div class="cart-product__amount">
                    <p class="cart-product__amount-text">{{ cart.products_price }} &#x20bd;</p>
                    </div>

                    <div class="cart-product__delete">
                        <a href="{% url "cart:cart_remove" %}" class="cart-product__delete-btn remove-from-cart"
                         data-cart-id="{{ cart.id }}">
                        {% csrf_token %}
                        <img
                            src="{% static 'images/cart-delete.svg' %}"
                            alt="delete"
                            class="cart-product__delete-img"
                        />
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</div>

<div class="cart__footer">
      <div class="cart__footer-group">
          <p class="cart__footer-text">Итого <strong>{{ carts.total_quantity }}</strong> товар(а) на сумму</p>
          <h5 class="cart__footer-amount">{{ carts.total_price }} &#x20bd;</h5>
      </div>
</div>

{% if carts and not order %}
    <a class="cart__btn" href="{% url "orders:create_order" %}">
    Оформить заказ
    </a>
{% endif %}


  