onlineFeedStore/main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("contacts", views.contacts, name="contacts"),
    path("feedback", views.feedback, name="feedback"),
]

onlineFeedStore/onlineFeedStore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "onlineFeedStore.views.error_404_view"

onlineFeedStore/users/urls.py
from django.urls import path

from users import views


app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("users-cart/", views.users_cart, name="users_cart"),
    path("logout/", views.logout, name="logout"),
]

onlineFeedStore/templates/includes/cart_popup.html
{% load static %}

{% load carts_tags %}
{% user_carts request as carts %}

<div class="cart_popup">
  <div class="cart_popup__inner">

    <h4 class="cart__title">Корзина</h4>
    
    <div id="cart-items-container">
      {% include "carts/includes/included_cart.html" %}
    </div>

    <div class="cart_popup__close">&#10006;</div>
    
  </div>
</div>

onlineFeedStore/templates/includes/footer.html
{% load static %}
<footer class="footer">
  <div class="container">
    <div class="footer__inner">
      
      <div class="footer__contacts">
        <div class="footer__contact">
          <p class="footer__contact-title footer__contact-title-map">Адрес</p>
          <p class="footer__contact-text">
            Ставропольский край,<br />
            г. Ставрополь,<br />
            просп. Кулакова, 2
          </p>
        </div>
        <div class="footer__contact">
          <p class="footer__contact-title footer__contact-title-mail">
            электронная почта
          </p>
          <a  class="footer__mail-link"
            >snadny.semen@yandex.ru</a
          >
        </div>
        <div class="footer__contact">
          <p class="footer__contact-title footer__contact-title-phone">
            телефон
          </p>
          <a class="footer__phone-link"
            >+ 7 (962) 413-75-96</a
          >
        </div>
      </div>
    </div>
  </div>
</footer>

onlineFeedStore/templates/includes/header.html
{% load static %}
{% load goods_tags %}
{% load mptt_tags %}
{% load carts_tags %}

<header class="header">
  <div class="container">
    <div class="header__inner">

      <!-- Nav -->
      <nav class="menu">
        <ul class="menu__list">
          <li class="menu__list-item">
            <a href="{% url "main:index" %}" class="menu__list-link">ГЛАВНАЯ</a>
          </li>
          
          <li class="menu__list-item menu__list-item_drop" >
            <a href="{% url "catalog:index" %}" class="menu__list-link menu__list-item-drop-link">АВТОЗАПЧАСТИ</a>
            <ul class="menu__sublist">
              
              {% tag_categories_kombi as categories %}
              {% recursetree categories %}
              <li class="menu__list-item menu__sublist-item">
                <a href="{% url "catalog:index" node.slug %}" class="menu__list-link menu__list-link-kombi"
                  >{{ node.name }}</a
                >
              </li>
              {% endrecursetree %}

            </ul>
          </li>


          {% if not user.is_authenticated %}
            <li class="menu__list-item">
              <a href="{% url "user:login" %}" class="menu__list-link"
                >Войти</a
              >
            </li>
          {% else %}
            <li class="menu__list-item menu__list-item_drop">
              <a href="{% url "user:profile" %}" class="menu__list-link menu__list-item-drop-link">ПРОФИЛЬ</a>
              <ul class="menu__sublist">
                <li class="menu__list-item menu__sublist-item">
                  <a href="{% url "user:profile" %}" class="menu__list-link"
                    >Личный кабинет</a
                  >
                </li>
                <li class="menu__list-item menu__sublist-item">
                  <a href="{% url "user:users_cart" %}" class="menu__list-link"
                    >Корзина</a
                  >
                </li>
                <li class="menu__list-item menu__sublist-item">
                  <a href="{% url "user:logout" %}" class="menu__list-link"
                    >Выйти</a
                  >
                </li>
      
                {% if user.is_admin or user.is_staff %}
                <li class="menu__list-item menu__sublist-item">
                  <a href="{% url "admin:index" %}" class="menu__list-link"
                    >Админ</a
                  >
                </li>
                {% endif %}
              </ul>
            </li>
          {% endif %}

          <li class="header__links">
            {% user_carts request as carts %}
            <div class="catalog__cart">
              <button type="button" class="menu__cart-btn cart_popup__open" id="modalButton"
                  aria-expanded="false">
                  <img class="catalog__cart-img" src="{% static 'images/catalog-cart.svg' %}" alt="Корзина">
                  <span class="catalog__cart-count" id="goods-in-cart-count">{{ carts.total_quantity }}</span>
              </button>
            </div>
          </li>

        </ul>
      </nav>

      

      <!-- Hamburger menu button -->
      <button class="menu__btn">
        <span></span>
        <span></span>
        <span></span>
      </button>

    </div>
  </div>
</header>

onlineFeedStore/templates/includes/header_no_cart.html
{% load static %}
{% load goods_tags %}
{% load mptt_tags %}
{% load carts_tags %}

<header class="header">
  <div class="container">
    <div class="header__inner">

      <!-- Nav -->
      <nav class="menu">
        <ul class="menu__list">
          <li class="menu__list-item">
            <a href="{% url "main:index" %}" class="menu__list-link">ГЛАВНАЯ</a>
          </li>
          
          <li class="menu__list-item menu__list-item_drop" >
            <a href="{% url "catalog:index" %}" class="menu__list-link menu__list-item-drop-link">АВТОЗАПЧАСТИ</a>
            <ul class="menu__sublist">
              
              {% tag_categories_kombi as categories %}
              {% recursetree categories %}
              <li class="menu__list-item menu__sublist-item">
                <a href="{% url "catalog:index" node.slug %}" class="menu__list-link menu__list-link-kombi"
                  >{{ node.name }}</a
                >
              </li>
              {% endrecursetree %}

            </ul>
          </li>


          {% if not user.is_authenticated %}
            <li class="menu__list-item">
              <a href="{% url "user:login" %}" class="menu__list-link"
                >Войти</a
              >
            </li>
          {% else %}
            <li class="menu__list-item menu__list-item_drop">
              <a href="{% url "user:profile" %}" class="menu__list-link menu__list-item-drop-link">ПРОФИЛЬ</a>
              <ul class="menu__sublist">
                <li class="menu__list-item menu__sublist-item">
                  <a href="{% url "user:profile" %}" class="menu__list-link"
                    >Личный кабинет</a
                  >
                </li>
                <li class="menu__list-item menu__sublist-item">
                  <a href="{% url "user:users_cart" %}" class="menu__list-link"
                    >Корзина</a
                  >
                </li>
                <li class="menu__list-item menu__sublist-item">
                  <a href="{% url "user:logout" %}" class="menu__list-link"
                    >Выйти</a
                  >
                </li>
      
                {% if user.is_admin or user.is_staff %}
                <li class="menu__list-item menu__sublist-item">
                  <a href="{% url "admin:index" %}" class="menu__list-link"
                    >Админ</a
                  >
                </li>
                {% endif %}
              </ul>
            </li>
          {% endif %}

          <li class="header__links">
            {% user_carts request as carts %}
            <div class="catalog__cart">
              <button type="button" class="menu__cart-btn cart_popup__open" id="modalButton"
                  aria-expanded="false">
                  <img class="catalog__cart-img" src="{% static 'images/catalog-cart.svg' %}" alt="Корзина">
                  <span class="catalog__cart-count" id="goods-in-cart-count">{{ carts.total_quantity }}</span>
              </button>
            </div>
          </li>

        </ul>
      </nav>

      

      <!-- Hamburger menu button -->
      <button class="menu__btn">
        <span></span>
        <span></span>
        <span></span>
      </button>

    </div>
  </div>
</header>

onlineFeedStore/templates/includes/notif_login.html
{% load static %}

{% if form.non_field_errors %}
    <div class="notif__inner">
      <div class="notif__alert-info" role="alert">
          {{form.non_field_errors}}
          <button type="button" class="notif__btn-close" aria-label="Close">&#10006;</button>
      </div>
    </div>
{% endif %}

onlineFeedStore/templates/includes/notifications.html
{% load static %}

<div class="notif-message__inner">
  {% if messages %}
      {% for message in messages %}
          {% if message.tags == 'success' %}
          <div id="notification" class="notif-message__text notif-message__text-success" role="alert">
              {{ message }}
          </div>
          {% endif %}
          {% if message.tags == 'warning' %}
          <div id="notification" class="notif-message__text notif-message__text-warning" role="alert">
              {{ message }}
          </div>
          {% endif %}
          {% if message.tags == 'error' %}
          <div id="notification" class="notif-message__text notif-message__text-error" role="alert">
              {{ message }}
          </div>
          {% endif %}
      {% endfor %}
  {% else %}
  <div id="jq-notification" class="notif-message__text notif-message__text-info" style="display: none;" role="alert">
  </div>
  {% endif %}
</div>

onlineFeedStore/templates/includes/popup.html
{% load static %}
<div class="popup" >
  <div class="popup__body" >
    <div class="popup__close">&#10006;</div>
  </div>
</div>